# uncompyle6 version 3.8.0
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
# Embedded file name: qt5.py
from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg, matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import os
BASE_DIR = os.path.dirname(os.path.realpath(__file__))

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(929, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName('centralwidget')
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName('gridLayout')
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName('splitter_4')
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName('layoutWidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.label_project_name = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project_name.sizePolicy().hasHeightForWidth())
        self.label_project_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_name.setFont(font)
        self.label_project_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_project_name.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_project_name.setObjectName('label_project_name')
        self.horizontalLayout.addWidget(self.label_project_name)
        self.label_project_item_name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_item_name.setFont(font)
        self.label_project_item_name.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_project_item_name.setObjectName('label_project_item_name')
        self.horizontalLayout.addWidget(self.label_project_item_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName('splitter_2')
        self.label_item_image = QtWidgets.QLabel(self.splitter_2)
        self.label_item_image.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_item_image.sizePolicy().hasHeightForWidth())
        self.label_item_image.setSizePolicy(sizePolicy)
        self.label_item_image.setMaximumSize(QtCore.QSize(800, 500))
        self.label_item_image.setText('')
        self.label_item_image.setPixmap(QtGui.QPixmap(':/newPrefix/messageImage_1600330717366.jpg'))
        self.label_item_image.setScaledContents(True)
        self.label_item_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_item_image.setObjectName('label_item_image')
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName('splitter')
        self.tableWidget_project_item = QtWidgets.QTableWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_project_item.sizePolicy().hasHeightForWidth())
        self.tableWidget_project_item.setSizePolicy(sizePolicy)
        self.tableWidget_project_item.setObjectName('tableWidget_project_item')
        self.tableWidget_project_item.setColumnCount(0)
        self.tableWidget_project_item.setRowCount(0)
        self.label_gonogo = QtWidgets.QLabel(self.splitter)
        self.label_gonogo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gonogo.sizePolicy().hasHeightForWidth())
        self.label_gonogo.setSizePolicy(sizePolicy)
        self.label_gonogo.setMaximumSize(QtCore.QSize(300, 400))
        self.label_gonogo.setObjectName('label_gonogo')
        self.verticalLayout.addWidget(self.splitter_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget1.setObjectName('layoutWidget1')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.label_project_item_name_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_item_name_2.setFont(font)
        self.label_project_item_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_item_name_2.setObjectName('label_project_item_name_2')
        self.verticalLayout_2.addWidget(self.label_project_item_name_2)
        self.splitter_3 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName('splitter_3')
        self.tableWidget_measure = QtWidgets.QTableWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_measure.sizePolicy().hasHeightForWidth())
        self.tableWidget_measure.setSizePolicy(sizePolicy)
        self.tableWidget_measure.setMaximumSize(QtCore.QSize(1250, 600))
        self.tableWidget_measure.setObjectName('tableWidget_measure')
        self.tableWidget_measure.setColumnCount(0)
        self.tableWidget_measure.setRowCount(0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_measure.sizePolicy().hasHeightForWidth())
        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.splitter_3.addWidget(self.canvas)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.gridLayout.addWidget(self.splitter_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName('menubar')
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName('statusbar')
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', '量測主視窗'))
        self.label_project_name.setText(_translate('MainWindow', '量測專案：'))
        self.label_project_item_name.setText(_translate('MainWindow', '量測項目：'))
        self.label_gonogo.setText(_translate('MainWindow', 'GONOGO'))
        self.label_project_item_name_2.setText(_translate('MainWindow', '量測人員：'))


class Ui_widget_projectcheck(object):

    def setupUi(self, widget):
        widget.setObjectName('widget')
        widget.resize(1108, 824)
        self.gridLayout = QtWidgets.QGridLayout(widget)
        self.gridLayout.setObjectName('gridLayout')
        self.splitter = QtWidgets.QSplitter(widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName('splitter')
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName('layoutWidget')
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName('verticalLayout_3')
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName('label')
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_rest_project = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rest_project.sizePolicy().hasHeightForWidth())
        self.pushButton_rest_project.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.pushButton_rest_project.setFont(font)
        self.pushButton_rest_project.setObjectName('pushButton_rest_project')
        self.horizontalLayout_2.addWidget(self.pushButton_rest_project)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tableWidget_project = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_project.setObjectName('tableWidget_project')
        self.tableWidget_project.setColumnCount(0)
        self.tableWidget_project.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_project)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName('layoutWidget1')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName('label_4')
        self.verticalLayout_2.addWidget(self.label_4)
        self.tableWidget_work_order = QtWidgets.QTableWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tableWidget_work_order.sizePolicy().hasHeightForWidth())
        self.tableWidget_work_order.setSizePolicy(sizePolicy)
        self.tableWidget_work_order.setObjectName('tableWidget_work_order')
        self.tableWidget_work_order.setColumnCount(0)
        self.tableWidget_work_order.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_work_order)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName('layoutWidget2')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName('label_2')
        self.verticalLayout.addWidget(self.label_2)
        self.tableWidget_measureitem = QtWidgets.QTableWidget(self.layoutWidget2)
        self.tableWidget_measureitem.setObjectName('tableWidget_measureitem')
        self.tableWidget_measureitem.setColumnCount(0)
        self.tableWidget_measureitem.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_measureitem)
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget3.setObjectName('layoutWidget3')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName('label_3')
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_now_project_name = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_now_project_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_now_project_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.lineEdit_now_project_name.setFont(font)
        self.lineEdit_now_project_name.setObjectName('lineEdit_now_project_name')
        self.horizontalLayout.addWidget(self.lineEdit_now_project_name)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName('label_6')
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_work_order_selet = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_work_order_selet.setObjectName('lineEdit_work_order_selet')
        self.horizontalLayout.addWidget(self.lineEdit_work_order_selet)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName('label_5')
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_measure_staff = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_measure_staff.sizePolicy().hasHeightForWidth())
        self.lineEdit_measure_staff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_measure_staff.setFont(font)
        self.lineEdit_measure_staff.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lineEdit_measure_staff.setObjectName('lineEdit_measure_staff')
        self.horizontalLayout.addWidget(self.lineEdit_measure_staff)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_cinfirm_project = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cinfirm_project.sizePolicy().hasHeightForWidth())
        self.pushButton_cinfirm_project.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.pushButton_cinfirm_project.setFont(font)
        self.pushButton_cinfirm_project.setObjectName('pushButton_cinfirm_project')
        self.horizontalLayout.addWidget(self.pushButton_cinfirm_project)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_close = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName('pushButton_close')
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate('widget', 'Form'))
        self.label.setText(_translate('widget', '1. 量測專案 \n Measurement project'))
        self.pushButton_rest_project.setText(_translate('widget', '重新整理專案 \n Reimport the project'))
        self.label_4.setText(_translate('widget', '2. 專案工單 \n work order'))
        self.label_2.setText(_translate('widget', '3. 量測項目 \n Measurement items'))
        self.label_3.setText(_translate('widget', '已選擇量測專案名稱  \n Selected  project name'))
        self.label_6.setText(_translate('widget', '已選擇工單名稱\nTicket name selected'))
        self.label_5.setText(_translate('widget', '量測人員 \nMeasuring staff'))
        self.pushButton_cinfirm_project.setText(_translate('widget', '選擇量測專案 \n Confirm project'))
        self.pushButton_close.setText(_translate('widget', '離開 \n Exit'))


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName('Form')
        Form.resize(682, 643)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 30, 571, 101))
        self.label.setText('')
        self.label.setPixmap(QtGui.QPixmap(BASE_DIR + '\\mp_logo.png'))
        self.label.setScaledContents(True)
        self.label.setObjectName('label')
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 140, 641, 116))
        self.layoutWidget.setObjectName('layoutWidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName('label_2')
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName('label_3')
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName('label_4')
        self.verticalLayout.addWidget(self.label_4)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(200, 270, 281, 343))
        self.layoutWidget_2.setObjectName('layoutWidget_2')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.tool_test = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tool_test.sizePolicy().hasHeightForWidth())
        self.tool_test.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.tool_test.setFont(font)
        self.tool_test.setObjectName('tool_test')
        self.verticalLayout_2.addWidget(self.tool_test)
        self.start_measure = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_measure.sizePolicy().hasHeightForWidth())
        self.start_measure.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.start_measure.setFont(font)
        self.start_measure.setObjectName('start_measure')
        self.verticalLayout_2.addWidget(self.start_measure)
        self.syste_setting = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syste_setting.sizePolicy().hasHeightForWidth())
        self.syste_setting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.syste_setting.setFont(font)
        self.syste_setting.setObjectName('syste_setting')
        self.verticalLayout_2.addWidget(self.syste_setting)
        self.excit = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.excit.sizePolicy().hasHeightForWidth())
        self.excit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.excit.setFont(font)
        self.excit.setObjectName('excit')
        self.verticalLayout_2.addWidget(self.excit)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate('Form', '生產線上雲端管理系統 - 無線量測系統'))
        self.label_2.setText(_translate('Form', '無線量測品管暨雲端可視化系統 - 品管量測端'))
        self.label_3.setText(_translate('Form', 'Wireless Measure and quality Control System'))
        self.label_4.setText(_translate('Form', ' with Cloud Visualization Integration-Client'))
        self.tool_test.setText(_translate('Form', '無線量具測試\nWireless measuring tool test'))
        self.start_measure.setText(_translate('Form', '開始量測\nStart measurement'))
        self.syste_setting.setText(_translate('Form', '系統設定\nsystem setting'))
        self.excit.setText(_translate('Form', '離開系統\nExit System'))


class Ui_toolcheck(object):

    def setupUi(self, Form):
        Form.setObjectName('Form')
        Form.resize(686, 587)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(9, 9, 661, 561))
        self.widget.setObjectName('widget')
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName('gridLayout')
        self.Button_tool_connect = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_tool_connect.sizePolicy().hasHeightForWidth())
        self.Button_tool_connect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Button_tool_connect.setFont(font)
        self.Button_tool_connect.setObjectName('Button_tool_connect')
        self.gridLayout.addWidget(self.Button_tool_connect, 1, 2, 1, 1)
        self.Button_tool_connect_rest = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_tool_connect_rest.sizePolicy().hasHeightForWidth())
        self.Button_tool_connect_rest.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Button_tool_connect_rest.setFont(font)
        self.Button_tool_connect_rest.setObjectName('Button_tool_connect_rest')
        self.gridLayout.addWidget(self.Button_tool_connect_rest, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName('label_2')
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName('label')
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_comname = QtWidgets.QComboBox(self.widget)
        self.comboBox_comname.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_comname.sizePolicy().hasHeightForWidth())
        self.comboBox_comname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_comname.setFont(font)
        self.comboBox_comname.setObjectName('comboBox_comname')
        self.gridLayout.addWidget(self.comboBox_comname, 0, 1, 1, 1)
        self.comboBox_tool_mount = QtWidgets.QComboBox(self.widget)
        self.comboBox_tool_mount.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_tool_mount.sizePolicy().hasHeightForWidth())
        self.comboBox_tool_mount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_tool_mount.setFont(font)
        self.comboBox_tool_mount.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.comboBox_tool_mount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_tool_mount.setAutoFillBackground(False)
        self.comboBox_tool_mount.setPlaceholderText('')
        self.comboBox_tool_mount.setObjectName('comboBox_tool_mount')
        self.comboBox_tool_mount.addItem('')
        self.comboBox_tool_mount.addItem('')
        self.comboBox_tool_mount.addItem('')
        self.comboBox_tool_mount.addItem('')
        self.gridLayout.addWidget(self.comboBox_tool_mount, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName('gridLayout_5')
        spacerItem = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName('pushButton_9')
        self.gridLayout_5.addWidget(self.pushButton_9, 1, 5, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName('pushButton_10')
        self.gridLayout_5.addWidget(self.pushButton_10, 0, 5, 1, 1)
        self.lineEdit_toolname = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.lineEdit_toolname.setFont(font)
        self.lineEdit_toolname.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_toolname.setReadOnly(False)
        self.lineEdit_toolname.setObjectName('lineEdit_toolname')
        self.gridLayout_5.addWidget(self.lineEdit_toolname, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 4, 1, 1)
        self.lineEdit_toolvalue = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        self.lineEdit_toolvalue.setFont(font)
        self.lineEdit_toolvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_toolvalue.setReadOnly(False)
        self.lineEdit_toolvalue.setObjectName('lineEdit_toolvalue')
        self.gridLayout_5.addWidget(self.lineEdit_toolvalue, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setScaledContents(False)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName('label_12')
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName('label_11')
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName('label_10')
        self.gridLayout_2.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName('label_5')
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate('Form', '無線量具測試'))
        self.Button_tool_connect.setText(_translate('Form', '量具連結\nMeasuring Tool Confirmation'))
        self.Button_tool_connect_rest.setText(_translate('Form', '量具重新連結\nMeasuring Tool Relink'))
        self.label_2.setText(_translate('Form', '連接量具數量\nMeasuretool '))
        self.label.setText(_translate('Form', '連接埠&裝置名稱\nCOM&Device name'))
        self.comboBox_tool_mount.setItemText(0, _translate('Form', '1'))
        self.comboBox_tool_mount.setItemText(1, _translate('Form', '2'))
        self.comboBox_tool_mount.setItemText(2, _translate('Form', '3'))
        self.comboBox_tool_mount.setItemText(3, _translate('Form', '4'))
        self.pushButton_9.setText(_translate('Form', '離開重設量具\nExit reconnect '))
        self.pushButton_10.setText(_translate('Form', '量具設定確認\nGage setting confirmation'))
        self.label_12.setText(_translate('Form', '裝置名稱\nDevice name'))
        self.label_11.setText(_translate('Form', '量測數值\nMeasurement Value'))
        self.label_10.setText(_translate('Form', '2. 量具測試\n     Measuring Tool Connection'))
        self.label_5.setText(_translate('Form', '1. 量測設定檢查\n     Measurement setting check'))


class Ui_check(object):

    def setupUi(self, Form):
        Form.setObjectName('Form')
        Form.resize(309, 209)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName('gridLayout')
        self.radioButton = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName('radioButton')
        self.gridLayout.addWidget(self.radioButton, 2, 1, 1, 3)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName('radioButton_2')
        self.gridLayout.addWidget(self.radioButton_2, 4, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.pushButton_setup = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setup.sizePolicy().hasHeightForWidth())
        self.pushButton_setup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(11)
        self.pushButton_setup.setFont(font)
        self.pushButton_setup.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_setup.setObjectName('pushButton_setup')
        self.gridLayout.addWidget(self.pushButton_setup, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 2, 1, 1)
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_exit.sizePolicy().hasHeightForWidth())
        self.pushButton_exit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(11)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_exit.setObjectName('pushButton_exit')
        self.gridLayout.addWidget(self.pushButton_exit, 6, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 6, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(8, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(8, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 3, 1, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(8, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 5, 1, 1, 3)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName('label')
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate('Form', '量測方式選擇'))
        self.radioButton.setText(_translate('Form', '依照零件部位'))
        self.radioButton_2.setText(_translate('Form', '依照件數'))
        self.pushButton_setup.setText(_translate('Form', '設定完成 \n Set up'))
        self.pushButton_exit.setText(_translate('Form', '離開 \n exit'))
        self.label.setText(_translate('Form', '選擇量測方式'))


class data_check(object):

    def setupUi(self, Form):
        Form.setObjectName('Form')
        Form.resize(483, 651)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName('gridLayout')
        self.pushButton_image = QtWidgets.QPushButton(Form)
        self.pushButton_image.setObjectName('pushButton_image')
        self.gridLayout.addWidget(self.pushButton_image, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName('label_3')
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setObjectName('label_image')
        self.gridLayout.addWidget(self.label_image, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName('label_6')
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName('label_5')
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.tableWidget_part = QtWidgets.QTableWidget(Form)
        self.tableWidget_part.setObjectName('tableWidget_part')
        self.tableWidget_part.setColumnCount(3)
        self.tableWidget_part.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_part.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_part.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_part.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget_part, 7, 0, 1, 4)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName('tableWidget')
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName('label_2')
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName('label')
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName('comboBox')
        self.gridLayout.addWidget(self.comboBox, 4, 1, 1, 1)
        self.lineEdit_remake = QtWidgets.QLineEdit(Form)
        self.lineEdit_remake.setObjectName('lineEdit_remake')
        self.gridLayout.addWidget(self.lineEdit_remake, 5, 1, 2, 2)
        self.pushButton_delet_image = QtWidgets.QPushButton(Form)
        self.pushButton_delet_image.setObjectName('pushButton_delet_image')
        self.gridLayout.addWidget(self.pushButton_delet_image, 5, 3, 1, 1)
        self.pushButton_insert_image = QtWidgets.QPushButton(Form)
        self.pushButton_insert_image.setObjectName('pushButton_insert_image')
        self.gridLayout.addWidget(self.pushButton_insert_image, 4, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName('pushButton_2')
        self.gridLayout.addWidget(self.pushButton_2, 8, 2, 1, 2)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName('pushButton')
        self.gridLayout.addWidget(self.pushButton, 8, 0, 1, 2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate('Form', 'Form'))
        self.pushButton_image.setText(_translate('Form', '選取'))
        self.label_3.setText(_translate('Form', '(1)選擇部位圖片'))
        self.label_image.setText(_translate('Form', '路徑'))
        self.label_6.setText(_translate('Form', '(2)件號'))
        self.label_5.setText(_translate('Form', '(3)備註'))
        item = self.tableWidget_part.horizontalHeaderItem(0)
        item.setText(_translate('Form', '件號'))
        item = self.tableWidget_part.horizontalHeaderItem(1)
        item.setText(_translate('Form', '部位圖片'))
        item = self.tableWidget_part.horizontalHeaderItem(2)
        item.setText(_translate('Form', '備註'))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate('Form', '量測數量'))
        self.label_2.setText(_translate('Form', '2.零件外觀'))
        self.label.setText(_translate('Form', '1.量測數據顯示'))
        self.pushButton_delet_image.setText(_translate('Form', '刪除'))
        self.pushButton_insert_image.setText(_translate('Form', '輸入'))
        self.pushButton_2.setText(_translate('Form', '離開取消上傳'))
        self.pushButton.setText(_translate('Form', '確認上傳'))


class measure_show_project(object):

    def setupUi(self, widget):
        widget.setObjectName('widget')
        widget.resize(670, 442)
        self.gridLayout_2 = QtWidgets.QGridLayout(widget)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.splitter_2 = QtWidgets.QSplitter(widget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName('splitter_2')
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName('widget')
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName('gridLayout')
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName('label')
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tableWidget_project = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_project.setObjectName('tableWidget_project')
        self.tableWidget_project.setColumnCount(0)
        self.tableWidget_project.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_project, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName('label_2')
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.tableWidget_work_order = QtWidgets.QTableWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_work_order.sizePolicy().hasHeightForWidth())
        self.tableWidget_work_order.setSizePolicy(sizePolicy)
        self.tableWidget_work_order.setSizeIncrement(QtCore.QSize(500, 500))
        self.tableWidget_work_order.setObjectName('tableWidget_work_order')
        self.tableWidget_work_order.setColumnCount(0)
        self.tableWidget_work_order.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_work_order, 3, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName('splitter')
        self.label_3 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName('label_3')
        self.tableWidget_measure_items = QtWidgets.QTableWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_measure_items.sizePolicy().hasHeightForWidth())
        self.tableWidget_measure_items.setSizePolicy(sizePolicy)
        self.tableWidget_measure_items.setObjectName('tableWidget_measure_items')
        self.tableWidget_measure_items.setColumnCount(0)
        self.tableWidget_measure_items.setRowCount(0)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate('widget', 'Form'))
        self.label.setText(_translate('widget', '1. 專案名稱'))
        self.label_2.setText(_translate('widget', '2. 工單'))
        self.label_3.setText(_translate('widget', '3. 量測項目'))


class Ui_Form_system_set(object):

    def setupUi(self, Form):
        Form.setObjectName('Form')
        Form.resize(345, 345)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName('tabWidget')
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName('tab_3')
        self.layoutWidget = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 302, 311))
        self.layoutWidget.setObjectName('layoutWidget')
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName('gridLayout')
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName('label')
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName('label_2')
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName('label_3')
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName('label_4')
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName('label_5')
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.sql_set_button = QtWidgets.QPushButton(self.layoutWidget)
        self.sql_set_button.setObjectName('sql_set_button')
        self.gridLayout.addWidget(self.sql_set_button, 5, 1, 1, 1)
        self.sql_reset_button_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.sql_reset_button_2.setObjectName('sql_reset_button_2')
        self.gridLayout.addWidget(self.sql_reset_button_2, 5, 2, 1, 1)
        self.lineEdit_host = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_host.setObjectName('lineEdit_host')
        self.gridLayout.addWidget(self.lineEdit_host, 0, 1, 1, 2)
        self.lineEdit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_name.setObjectName('lineEdit_name')
        self.gridLayout.addWidget(self.lineEdit_name, 1, 1, 1, 2)
        self.lineEdit_user = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_user.setObjectName('lineEdit_user')
        self.gridLayout.addWidget(self.lineEdit_user, 2, 1, 1, 2)
        self.lineEdit_charset = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_charset.setObjectName('lineEdit_charset')
        self.gridLayout.addWidget(self.lineEdit_charset, 3, 1, 1, 2)
        self.lineEdit_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password.setObjectName('lineEdit_password')
        self.gridLayout.addWidget(self.lineEdit_password, 4, 1, 1, 2)
        self.sql_reply_button_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.sql_reply_button_2.setObjectName('sql_reply_button_2')
        self.gridLayout.addWidget(self.sql_reply_button_2, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, '')
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName('tab_4')
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 301, 321))
        self.layoutWidget1.setObjectName('layoutWidget1')
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName('gridLayout_3')
        self.pushButton_tool_set = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_tool_set.setObjectName('pushButton_tool_set')
        self.gridLayout_3.addWidget(self.pushButton_tool_set, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName('label_6')
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_2.setObjectName('comboBox_2')
        self.comboBox_2.addItem('')
        self.comboBox_2.addItem('')
        self.comboBox_2.addItem('')
        self.gridLayout_3.addWidget(self.comboBox_2, 2, 2, 1, 2)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_3.setObjectName('comboBox_3')
        self.comboBox_3.addItem('')
        self.comboBox_3.addItem('')
        self.comboBox_3.addItem('')
        self.gridLayout_3.addWidget(self.comboBox_3, 3, 2, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName('lineEdit_3')
        self.gridLayout_3.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.pushButton_tool_reset = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_tool_reset.setObjectName('pushButton_tool_reset')
        self.gridLayout_3.addWidget(self.pushButton_tool_reset, 4, 2, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setObjectName('comboBox')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.gridLayout_3.addWidget(self.comboBox, 1, 2, 1, 2)
        self.pushButton_tool_set_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_tool_set_2.setObjectName('pushButton_tool_set_2')
        self.gridLayout_3.addWidget(self.pushButton_tool_set_2, 4, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName('lineEdit')
        self.gridLayout_3.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setObjectName('lineEdit_2')
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName('label_7')
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName('label_8')
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName('label_9')
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName('label_10')
        self.gridLayout_3.addWidget(self.label_10, 0, 1, 1, 1)
        self.pushButton_create_tool = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_create_tool.setObjectName('pushButton_create_tool')
        self.gridLayout_3.addWidget(self.pushButton_create_tool, 0, 2, 1, 2)
        self.tabWidget.addTab(self.tab_4, '')
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate('Form', 'Form'))
        self.label.setText(_translate('Form', '主機'))
        self.label_2.setText(_translate('Form', '名稱 '))
        self.label_3.setText(_translate('Form', '用戶'))
        self.label_4.setText(_translate('Form', '編碼'))
        self.label_5.setText(_translate('Form', '密碼'))
        self.sql_set_button.setText(_translate('Form', '資料庫設置確認'))
        self.sql_reset_button_2.setText(_translate('Form', '清除資料重新設置'))
        self.sql_reply_button_2.setText(_translate('Form', '回復預設資料'))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate('Form', '連線資料庫設定'))
        self.pushButton_tool_set.setText(_translate('Form', '量具設定確認'))
        self.label_6.setText(_translate('Form', '連接COM1'))
        self.comboBox_2.setItemText(0, _translate('Form', '游標卡尺'))
        self.comboBox_2.setItemText(1, _translate('Form', '分厘卡'))
        self.comboBox_2.setItemText(2, _translate('Form', '高度規'))
        self.comboBox_3.setItemText(0, _translate('Form', '游標卡尺'))
        self.comboBox_3.setItemText(1, _translate('Form', '分厘卡'))
        self.comboBox_3.setItemText(2, _translate('Form', '高度規'))
        self.pushButton_tool_reset.setText(_translate('Form', '清除資料重新設置'))
        self.comboBox.setItemText(0, _translate('Form', '游標卡尺'))
        self.comboBox.setItemText(1, _translate('Form', '分厘卡'))
        self.comboBox.setItemText(2, _translate('Form', '高度規'))
        self.pushButton_tool_set_2.setText(_translate('Form', '回復量俱設定'))
        self.label_7.setText(_translate('Form', '連接COM2'))
        self.label_8.setText(_translate('Form', '連接COM3'))
        self.label_9.setText(_translate('Form', 'USB_PORT'))
        self.label_10.setText(_translate('Form', '量測數值'))
        self.pushButton_create_tool.setText(_translate('Form', '新增量具'))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate('Form', '量具連接設定'))


class tool_create(object):

    def setupUi(self, widget):
        widget.setObjectName('widget')
        widget.resize(300, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget.sizePolicy().hasHeightForWidth())
        widget.setSizePolicy(sizePolicy)
        widget.setMinimumSize(QtCore.QSize(300, 299))
        widget.setMaximumSize(QtCore.QSize(300, 300))
        self.gridLayout_2 = QtWidgets.QGridLayout(widget)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName('gridLayout')
        self.pushButton_measure_tool_create = QtWidgets.QPushButton(widget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_measure_tool_create.setFont(font)
        self.pushButton_measure_tool_create.setObjectName('pushButton_measure_tool_create')
        self.gridLayout.addWidget(self.pushButton_measure_tool_create, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(widget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName('label')
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(widget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName('label_3')
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.tableWidget_measure_tool = QtWidgets.QTableWidget(widget)
        self.tableWidget_measure_tool.setObjectName('tableWidget_measure_tool')
        self.tableWidget_measure_tool.setColumnCount(0)
        self.tableWidget_measure_tool.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_measure_tool, 1, 0, 1, 3)
        self.pushButton_measure_tool_del = QtWidgets.QPushButton(widget)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_measure_tool_del.setFont(font)
        self.pushButton_measure_tool_del.setObjectName('pushButton_measure_tool_del')
        self.gridLayout.addWidget(self.pushButton_measure_tool_del, 3, 2, 1, 1)
        self.lineEdit_create_tool = QtWidgets.QLineEdit(widget)
        self.lineEdit_create_tool.setObjectName('lineEdit_create_tool')
        self.gridLayout.addWidget(self.lineEdit_create_tool, 2, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate('widget', '量具新增'))
        self.pushButton_measure_tool_create.setText(_translate('widget', '確認新增'))
        self.label.setText(_translate('widget', '新增量具名稱'))
        self.label_3.setText(_translate('widget', '量具列表'))
        self.pushButton_measure_tool_del.setText(_translate('widget', '刪除名稱'))


class appearance_affect(object):

    def setupUi(self, Form):
        Form.setObjectName('Form')
        Form.resize(527, 541)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName('gridLayout')
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName('label_2')
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName('label')
        self.gridLayout.addWidget(self.label, 0, 0, 1, 7)
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName('label_5')
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.pushButton_delet = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.pushButton_delet.setFont(font)
        self.pushButton_delet.setObjectName('pushButton_delet')
        self.gridLayout.addWidget(self.pushButton_delet, 4, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName('label_3')
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.pushButton_insert = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.pushButton_insert.setFont(font)
        self.pushButton_insert.setObjectName('pushButton_insert')
        self.gridLayout.addWidget(self.pushButton_insert, 3, 8, 1, 1)
        self.tableWidget_appearnance_affect = QtWidgets.QTableWidget(Form)
        self.tableWidget_appearnance_affect.setObjectName('tableWidget_appearnance_affect')
        self.tableWidget_appearnance_affect.setColumnCount(0)
        self.tableWidget_appearnance_affect.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_appearnance_affect, 5, 0, 1, 9)
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setObjectName('pushButton')
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)
        self.textEdit_remake = QtWidgets.QTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_remake.sizePolicy().hasHeightForWidth())
        self.textEdit_remake.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.textEdit_remake.setFont(font)
        self.textEdit_remake.setObjectName('textEdit_remake')
        self.gridLayout.addWidget(self.textEdit_remake, 3, 2, 2, 6)
        self.label_image_url = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_url.sizePolicy().hasHeightForWidth())
        self.label_image_url.setSizePolicy(sizePolicy)
        self.label_image_url.setMaximumSize(QtCore.QSize(1200, 16777215))
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.label_image_url.setFont(font)
        self.label_image_url.setObjectName('label_image_url')
        self.gridLayout.addWidget(self.label_image_url, 2, 3, 1, 6)
        self.label_part_number = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily('微軟正黑體')
        font.setPointSize(12)
        self.label_part_number.setFont(font)
        self.label_part_number.setObjectName('label_part_number')
        self.gridLayout.addWidget(self.label_part_number, 1, 2, 1, 1)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate('Form', '外觀輸入'))
        self.label_2.setText(_translate('Form', '1. 零件編號'))
        self.label.setText(_translate('Form', '輸入零件外觀'))
        self.label_5.setText(_translate('Form', '2. 外觀圖片'))
        self.pushButton_delet.setText(_translate('Form', '刪除'))
        self.label_3.setText(_translate('Form', '3. 備註'))
        self.pushButton_insert.setText(_translate('Form', '輸入'))
        self.pushButton.setText(_translate('Form', '路徑'))
        self.label_image_url.setText(_translate('Form', '圖片路徑'))
        self.label_part_number.setText(_translate('Form', '123'))
# okay decompiling qt5.pyc
